module Morse
    # Decodes the character from Morse Code
    def Morse.decode_char(char)
        case char
        when ".-"
            return "a"
        when ".---"
            return "b"
        when "-.-."
            return "c"
        when "-.."
            return "d"
        when "."
            return "e"
        when "..-."
            return "f"
        when "--."
            return "g"
        when "...."
            return "h"
        when ".."
            return "i"
        when ".---"
            return "j"
        when "-.-"
            return "k"
        when ".-.."
            return "l"
        when "--"
            return "m"
        when "-."
            return "n"
        when "---"
            return "o"
        when ".--."
            return "p"
        when "--.-"
            return "q"
        when ".-."
            return "r"
        when "..."
            return "s"
        when "-"
            return "t"
        when "..-"
            return "u"
        when "...-"
            return "v"
        when ".--"
            return "w"
        when "-..-"
            return "x"
        when "-.--"
            return "y"
        when "--.."
            return "z"
        else
            raise "Invalid Character"
        end
    end
    # Encodes the character in Morse Code
    def Morse.encode_char(char)
        char.downcase! # Deals with privaged upper-case children
        case char
        when "a"
            return ".-"
        when "b"
                return ".---"
        when "c"
                return "-.-."
        when "d"
                return "-.."
        when "e"
                return "."
        when "f"
                return "..-."
        when "g"
                return "--."
        when "h"
                return "...."
        when "i"
                return ".."
        when "b"
                return ".---"
        when "k"
                return "-.-"
        when "l"
                return ".-.."
        when "m"
                return "--"
        when "n"
                return "-."
        when "o"
                return "---"
        when "p"
                return ".--."
        when "q"
                return "--.-"
        when "r"
                return ".-."
        when "s"
                return "..."
        when "t"
                return "-"
        when "u"
                return "..-"
        when "v"
                return "...-"
        when "w"
                return ".--"
        when "x"
                return "-..-"
        when "y"
                return "-.--"
        when "z"
                return "--.."    
        else
            raise "Invalid Character"
        end
    end
end